runtime: python
runtime_config:
  python_version: 3
env: flex
entrypoint: gunicorn wsgi:app --timeout 180

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
health_check:
  enable_health_check: false
